import type { Metadata } from "next";
import { Inter,Roboto_Condensed } from 'next/font/google'
import "./globals.css";
import { Header,Footer } from "@/components/index";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoCondensed.variable} antialiased relative`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
